module load python/3.7.4 
sbatch script/EELC_pairwise_0.sh
sbatch script/EELC_pairwise_1.sh
sbatch script/EELC_pairwise_2.sh
sbatch script/EELC_pairwise_3.sh
sbatch script/EELC_pairwise_4.sh
sbatch script/EELC_pairwise_5.sh
sbatch script/EELC_pairwise_6.sh
sbatch script/EELC_pairwise_7.sh
sbatch script/EELC_pairwise_8.sh
sbatch script/EELC_pairwise_9.sh
sbatch script/EELC_pairwise_10.sh
sbatch script/EELC_pairwise_11.sh
sbatch script/EELC_pairwise_12.sh
sbatch script/EELC_pairwise_13.sh
sbatch script/EELC_pairwise_14.sh
sbatch script/EELC_pairwise_15.sh
sbatch script/EELC_pairwise_16.sh
sbatch script/EELC_pairwise_17.sh
sbatch script/EELC_pairwise_18.sh
sbatch script/EELC_pairwise_19.sh
sbatch script/EELC_pairwise_20.sh
sbatch script/EELC_pairwise_21.sh
sbatch script/EELC_pairwise_22.sh
sbatch script/EELC_pairwise_23.sh
sbatch script/EELC_pairwise_24.sh
sbatch script/EELC_pairwise_25.sh
sbatch script/EELC_pairwise_26.sh
sbatch script/EELC_pairwise_27.sh
sbatch script/EELC_pairwise_28.sh
sbatch script/EELC_pairwise_29.sh
sbatch script/EELC_pairwise_30.sh
sbatch script/EELC_pairwise_31.sh
sbatch script/EELC_pairwise_32.sh
sbatch script/EELC_pairwise_33.sh
sbatch script/EELC_pairwise_34.sh
sbatch script/EELC_pairwise_35.sh
sbatch script/EELC_pairwise_36.sh
sbatch script/EELC_pairwise_37.sh
sbatch script/EELC_pairwise_38.sh
sbatch script/EELC_pairwise_39.sh
sbatch script/EELC_pairwise_40.sh
sbatch script/EELC_pairwise_41.sh
sbatch script/EELC_pairwise_42.sh
sbatch script/EELC_pairwise_43.sh
sbatch script/EELC_pairwise_44.sh
sbatch script/EELC_pairwise_45.sh
sbatch script/EELC_pairwise_46.sh
sbatch script/EELC_pairwise_47.sh
sbatch script/EELC_pairwise_48.sh
sbatch script/EELC_pairwise_49.sh
sbatch script/EELC_pairwise_50.sh
sbatch script/EELC_pairwise_51.sh
sbatch script/EELC_pairwise_52.sh
sbatch script/EELC_pairwise_53.sh
sbatch script/EELC_pairwise_54.sh
sbatch script/EELC_pairwise_55.sh
sbatch script/EELC_pairwise_56.sh
sbatch script/EELC_pairwise_57.sh
sbatch script/EELC_pairwise_58.sh
sbatch script/EELC_pairwise_59.sh
sbatch script/EELC_pairwise_60.sh
sbatch script/EELC_pairwise_61.sh
sbatch script/EELC_pairwise_62.sh
sbatch script/EELC_pairwise_63.sh
sbatch script/EELC_pairwise_64.sh
sbatch script/EELC_pairwise_65.sh
sbatch script/EELC_pairwise_66.sh
sbatch script/EELC_pairwise_67.sh
sbatch script/EELC_pairwise_68.sh
sbatch script/EELC_pairwise_69.sh
sbatch script/EELC_pairwise_70.sh
sbatch script/EELC_pairwise_71.sh
sbatch script/EELC_pairwise_72.sh
sbatch script/EELC_pairwise_73.sh
sbatch script/EELC_pairwise_74.sh
sbatch script/EELC_pairwise_75.sh
sbatch script/EELC_pairwise_76.sh
sbatch script/EELC_pairwise_77.sh
sbatch script/EELC_pairwise_78.sh
sbatch script/EELC_pairwise_79.sh
sbatch script/EELC_pairwise_80.sh
sbatch script/EELC_pairwise_81.sh
sbatch script/EELC_pairwise_82.sh
sbatch script/EELC_pairwise_83.sh
sbatch script/EELC_pairwise_84.sh
sbatch script/EELC_pairwise_85.sh
sbatch script/EELC_pairwise_86.sh
sbatch script/EELC_pairwise_87.sh
sbatch script/EELC_pairwise_88.sh
sbatch script/EELC_pairwise_89.sh
sbatch script/EELC_pairwise_90.sh
sbatch script/EELC_pairwise_91.sh
sbatch script/EELC_pairwise_92.sh
sbatch script/EELC_pairwise_93.sh
sbatch script/EELC_pairwise_94.sh
sbatch script/EELC_pairwise_95.sh
sbatch script/EELC_pairwise_96.sh
sbatch script/EELC_pairwise_97.sh
sbatch script/EELC_pairwise_98.sh
sbatch script/EELC_pairwise_99.sh
