module load python/3.7.4 
sbatch script/EELC_seven_dyn_0.sh
sbatch script/EELC_seven_dyn_1.sh
sbatch script/EELC_seven_dyn_2.sh
sbatch script/EELC_seven_dyn_3.sh
sbatch script/EELC_seven_dyn_4.sh
sbatch script/EELC_seven_dyn_5.sh
sbatch script/EELC_seven_dyn_6.sh
sbatch script/EELC_seven_dyn_7.sh
sbatch script/EELC_seven_dyn_8.sh
sbatch script/EELC_seven_dyn_9.sh
sbatch script/EELC_seven_dyn_10.sh
sbatch script/EELC_seven_dyn_11.sh
sbatch script/EELC_seven_dyn_12.sh
sbatch script/EELC_seven_dyn_13.sh
sbatch script/EELC_seven_dyn_14.sh
sbatch script/EELC_seven_dyn_15.sh
sbatch script/EELC_seven_dyn_16.sh
sbatch script/EELC_seven_dyn_17.sh
sbatch script/EELC_seven_dyn_18.sh
sbatch script/EELC_seven_dyn_19.sh
sbatch script/EELC_seven_dyn_20.sh
sbatch script/EELC_seven_dyn_21.sh
sbatch script/EELC_seven_dyn_22.sh
sbatch script/EELC_seven_dyn_23.sh
sbatch script/EELC_seven_dyn_24.sh
sbatch script/EELC_seven_dyn_25.sh
sbatch script/EELC_seven_dyn_26.sh
sbatch script/EELC_seven_dyn_27.sh
sbatch script/EELC_seven_dyn_28.sh
sbatch script/EELC_seven_dyn_29.sh
sbatch script/EELC_seven_dyn_30.sh
sbatch script/EELC_seven_dyn_31.sh
sbatch script/EELC_seven_dyn_32.sh
sbatch script/EELC_seven_dyn_33.sh
sbatch script/EELC_seven_dyn_34.sh
sbatch script/EELC_seven_dyn_35.sh
sbatch script/EELC_seven_dyn_36.sh
sbatch script/EELC_seven_dyn_37.sh
sbatch script/EELC_seven_dyn_38.sh
sbatch script/EELC_seven_dyn_39.sh
sbatch script/EELC_seven_dyn_40.sh
sbatch script/EELC_seven_dyn_41.sh
sbatch script/EELC_seven_dyn_42.sh
sbatch script/EELC_seven_dyn_43.sh
sbatch script/EELC_seven_dyn_44.sh
sbatch script/EELC_seven_dyn_45.sh
sbatch script/EELC_seven_dyn_46.sh
sbatch script/EELC_seven_dyn_47.sh
sbatch script/EELC_seven_dyn_48.sh
sbatch script/EELC_seven_dyn_49.sh
sbatch script/EELC_seven_dyn_50.sh
sbatch script/EELC_seven_dyn_51.sh
sbatch script/EELC_seven_dyn_52.sh
sbatch script/EELC_seven_dyn_53.sh
sbatch script/EELC_seven_dyn_54.sh
sbatch script/EELC_seven_dyn_55.sh
sbatch script/EELC_seven_dyn_56.sh
sbatch script/EELC_seven_dyn_57.sh
sbatch script/EELC_seven_dyn_58.sh
sbatch script/EELC_seven_dyn_59.sh
sbatch script/EELC_seven_dyn_60.sh
sbatch script/EELC_seven_dyn_61.sh
sbatch script/EELC_seven_dyn_62.sh
sbatch script/EELC_seven_dyn_63.sh
sbatch script/EELC_seven_dyn_64.sh
sbatch script/EELC_seven_dyn_65.sh
sbatch script/EELC_seven_dyn_66.sh
sbatch script/EELC_seven_dyn_67.sh
sbatch script/EELC_seven_dyn_68.sh
sbatch script/EELC_seven_dyn_69.sh
sbatch script/EELC_seven_dyn_70.sh
sbatch script/EELC_seven_dyn_71.sh
sbatch script/EELC_seven_dyn_72.sh
sbatch script/EELC_seven_dyn_73.sh
sbatch script/EELC_seven_dyn_74.sh
sbatch script/EELC_seven_dyn_75.sh
sbatch script/EELC_seven_dyn_76.sh
sbatch script/EELC_seven_dyn_77.sh
sbatch script/EELC_seven_dyn_78.sh
sbatch script/EELC_seven_dyn_79.sh
sbatch script/EELC_seven_dyn_80.sh
sbatch script/EELC_seven_dyn_81.sh
sbatch script/EELC_seven_dyn_82.sh
sbatch script/EELC_seven_dyn_83.sh
sbatch script/EELC_seven_dyn_84.sh
sbatch script/EELC_seven_dyn_85.sh
sbatch script/EELC_seven_dyn_86.sh
sbatch script/EELC_seven_dyn_87.sh
sbatch script/EELC_seven_dyn_88.sh
sbatch script/EELC_seven_dyn_89.sh
sbatch script/EELC_seven_dyn_90.sh
sbatch script/EELC_seven_dyn_91.sh
sbatch script/EELC_seven_dyn_92.sh
sbatch script/EELC_seven_dyn_93.sh
sbatch script/EELC_seven_dyn_94.sh
sbatch script/EELC_seven_dyn_95.sh
sbatch script/EELC_seven_dyn_96.sh
sbatch script/EELC_seven_dyn_97.sh
sbatch script/EELC_seven_dyn_98.sh
sbatch script/EELC_seven_dyn_99.sh
